import { APP_CATEGORIES } from '@/constants/categories';

// Shared unified category list — identical to the Post Enquiry form.
export const SELL_CATEGORIES = APP_CATEGORIES;

export const SELL_LOCATIONS: string[] = [
  'Mumbai',
  'Delhi',
  'Bengaluru',
  'Hyderabad',
  'Chennai',
  'Kolkata',
  'Pune',
  'Ahmedabad',
  'Jaipur',
  'Lucknow',
  'Kanpur',
  'Nagpur',
  'Indore',
  'Thane',
  'Bhopal',
  'Visakhapatnam',
  'Patna',
  'Vadodara',
  'Ghaziabad',
  'Ludhiana',
  'Agra',
  'Nashik',
  'Surat',
  'Varanasi',
  'Srinagar',
  'Aurangabad',
  'Navi Mumbai',
  'Solapur',
  'Vijayawada',
  'Ranchi',
  'Howrah',
  'Coimbatore',
  'Kochi',
  'Mysuru',
  'Jodhpur',
  'Guwahati',
  'Thiruvananthapuram',
  'Dehradun',
  'Chandigarh',
  'Goa',
  'Other',
];


