// Shared category icon mapping — single source of truth used by the
// Post Enquiry picker, the Likes page, and anywhere else categories
// need a visual. Icons come from lucide-react.
import {
  Briefcase, User, Wrench, Tractor, Landmark, Palette, Car, Bike, Smartphone,
  Monitor, Sofa, Baby, BookOpen, Flower2, Users, Trophy, HardHat, GraduationCap,
  Film, PartyPopper, Shirt, UtensilsCrossed, Gamepad2, Building2, HeartPulse,
  ShieldCheck, Gem, Scale, Megaphone, Stamp, HandHeart, PawPrint, Factory,
  Home, Zap, Lock, MapPin, Dumbbell, Truck, Mic, Camera, TreePine, FileText,
  Sparkles, Music, MoreHorizontal, LayoutGrid, Footprints,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  "business": Briefcase,
  "personal": User,
  "service": Wrench,
  "agriculture-farming": Tractor,
  "antiques": Landmark,
  "art": Palette,
  "automobile": Car,
  "car": Car,
  "bike": Bike,
  "mobiles": Smartphone,
  "laptops": Monitor,
  "furniture": Sofa,
  "vehicles": Car,
  "baby-kids": Baby,
  "bags-luggage": Briefcase,
  "books-publications": BookOpen,
  "beauty-products": Flower2,
  "bicycles": Bike,
  "childcare-family": Users,
  "collectibles": Trophy,
  "construction-renovation": HardHat,
  "education-training": GraduationCap,
  "electronics": Smartphone,
  "electronics-gadgets": Monitor,
  "entertainment-media": Film,
  "events-entertainment": PartyPopper,
  "fashion": Shirt,
  "fashion-apparel": Shirt,
  "food-beverage": UtensilsCrossed,
  "gaming-recreation": Gamepad2,
  "government-public": Building2,
  "health-beauty": HeartPulse,
  "home-furniture": Sofa,
  "insurance-services": ShieldCheck,
  "jobs": Briefcase,
  "jewelry-accessories": Gem,
  "legal-financial": Scale,
  "marketing-advertising": Megaphone,
  "memorabilia": Stamp,
  "non-profit-charity": HandHeart,
  "pets": PawPrint,
  "raw-materials-industrial": Factory,
  "real-estate": Home,
  "real-estate-services": Home,
  "renewable-energy": Zap,
  "security-safety": Lock,
  "sneakers": Footprints,
  "souvenir": MapPin,
  "sports-outdoor": Dumbbell,
  "technology": Monitor,
  "thrift": Shirt,
  "transportation-logistics": Truck,
  "travel-tourism": MapPin,
  "vintage": Landmark,
  "waste-management": Factory,
  "wedding-events": PartyPopper,
  "musical-instruments": Mic,
  "tools-equipment": Wrench,
  "appliances": Sofa,
  "photography-cameras": Camera,
  "fitness-gym-equipment": Dumbbell,
  "kitchen-dining": UtensilsCrossed,
  "garden-outdoor": TreePine,
  "office-supplies": FileText,
  "repair-services": Wrench,
  "cleaning-services": Sparkles,
  "musical-services": Mic,
  "tutoring-lessons": GraduationCap,
  "medical-equipment": HeartPulse,
  "musical-accessories": Music,
  "other": MoreHorizontal,
};

// Fallback for any value not in the map (e.g. legacy DB values).
export const getCategoryIcon = (value: string | undefined | null): LucideIcon =>
  (value && CATEGORY_ICONS[value]) || LayoutGrid;
