// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ervsfadfervihhzykyfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVydnNmYWRmZXJ2aWhoenlreWZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1ODk4MDUsImV4cCI6MjA3MDE2NTgwNX0.x1dGI76GzVurD8PzmW0SVF2D3AxvL4nmWkC1CG5EwA0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});